FROM node:lts-alpine

ARG VELA_GITHUB_TOKEN

WORKDIR /app

COPY . ./

EXPOSE 5173

RUN echo ${VELA_GITHUB_TOKEN}
RUN yarn config set proxy http://web.prod.proxy.cargill.com:4200
RUN yarn config set https-proxy http://web.prod.proxy.cargill.com:4200
RUN yarn config set cafile cacerts/ca_bundle.pem
RUN yarn install 
CMD ["yarn", "dev"]
