---
kind: static-website
app: &app_name localdevreactviteapp
team: apacappenablement
internal: true
package:
  build_dir: dist/
  index_document: index.html
dns:
  zone: cglcloud
  name: *app_name
headers:
  csp:
    default:
      script-src:
        self: true
        unsafe-inline: true
        unsafe-eval: true
        blob: true
      style-src:
        self: true
        unsafe-inline: true
        unsafe-eval: true
        sources:
          - https://fonts.googleapis.com
      font-src:
        sources:
          - https://fonts.gstatic.com
      media-src:
        self: true
      img-src:
        self: true
        data: true
      manifest-src:
        self: true
      connect-src:
        self: true
        sources:
          - https://rum.browser-intake-datadoghq.com
          - https://logs.browser-intake-datadoghq.com
          - https://session-replay.browser-intake-datadoghq.com

