FROM python:3.12-slim-bullseye AS base

# https://docs.docker.com/reference/dockerfile/#arg
# ARG HTTP_PROXY
# ARG HTTPS_PROXY

ENV PYTHONUNBUFFERED 1
ENV POETRY_VERSION 1.8.2
ENV POETRY_REQUESTS_TIMEOUT 60

COPY ./cacerts/*.pem /usr/local/share/ca-certificates/

RUN apt-get -y update && \
  pip config set global.trusted-host "pypi.org files.pythonhosted.org pypi.python.org" && \
  pip install --no-cache-dir certifi && \
  python -c "import certifi; import glob; writer=open(certifi.where(), 'ab'); [writer.write(open(f,'rb').read()) for f in glob.glob('/usr/local/share/ca-certificates/*.pem')]; writer.close()" && \
  update-ca-certificates && \
  pip install --upgrade --no-cache-dir pip && \
  apt-get --no-install-recommends --assume-yes install tzdata libpq5 libmagic1 && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/*

RUN pip install --default-timeout=60 "poetry==$POETRY_VERSION"
WORKDIR /app
ENV PYTHONPATH=/app/app
COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false
RUN poetry lock --no-update
RUN poetry install --no-interaction --no-ansi --only main --no-root
COPY . .
