// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, ItemsCreateItemData, ItemsCreateItemResponse, UtilsHealthCheckResponse } from './types.gen';

/**
 * Login Access Token
 * OAuth2 compatible token login, get an access token for future requests
 * @param data The data for the request.
 * @param data.formData
 * @returns Token Successful Response
 * @throws ApiError
 */
export const loginLoginAccessToken = (data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/python/api/v1/login/access-token',
    formData: data.formData,
    mediaType: 'application/x-www-form-urlencoded',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Test Token
 * Test access token
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const loginTestToken = (): CancelablePromise<LoginTestTokenResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/python/api/v1/login/test-token'
}); };

/**
 * Create User
 * Create new user.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const usersCreateUser = (data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/python/api/v1/users/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read User Me
 * Get current user.
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const usersReadUserMe = (): CancelablePromise<UsersReadUserMeResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/python/api/v1/users/me'
}); };

/**
 * Create Item
 * Create new item.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns ItemPublic Successful Response
 * @throws ApiError
 */
export const itemsCreateItem = (data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/python/api/v1/items/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Health Check
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const utilsHealthCheck = (): CancelablePromise<UtilsHealthCheckResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/python/api/v1/utils/health'
}); };