metadata:
  template: true
  # list of vars that this template can consume
  # vars
  # package_dir

# https://go-vela.github.io/docs/templates/
# https://go-vela.github.io/docs/templates/tutorials/go/
# https://pkg.go.dev/text/template

steps:
  - name: install-react
    image: node:20-slim
    ruleset:
      if:
        event: [push]
        branch: main
        path: ["react-vite-ts/*"]
    commands:
      - corepack enable pnpm
      - cd react-vite-ts
      - pnpm install
  - name: build-react
    image: node:20-slim
    ruleset:
      if:
        event: [push]
        branch: main
        path: ["react-vite-ts/*"]
    commands:
      - corepack enable pnpm
      - cd react-vite-ts
      - pnpm build
