metadata:
  template: true
  # list of vars that this template can consume
  # vars
  # package_dir

# https://go-vela.github.io/docs/templates/
# https://go-vela.github.io/docs/templates/tutorials/go/
# https://pkg.go.dev/text/template

steps:
  - name: docker-python
    image: docker-utilities.binrepo.cglcloud.in/enablementtools/docker-plugin:3-stable
    ruleset:
      if:
        event: [push]
        branch: [main]
        path: ["python/*"]
    parameters:
      repo: localdevpythonapp
      tags: "${VELA_BUILD_COMMIT:0:7}"
      dockerfile: python/Dockerfile
