---
version: "1"

metadata:
  auto_cancel:
    pending: true
    default_branch: true
    running: true

secrets:
  - name: VELA_GITHUB_TOKEN
    key: engineering-apac-tech-services/local-dev/VELA_GITHUB_TOKEN
    engine: native
    type: repo

templates:
  - name: java
    source: .vela-build-java-template.yml
    type: file
  - name: react
    source: .vela-build-react-template.yml
    type: file
  - name: react-vite-ts
    source: .vela-build-react-vite-template.yml
    type: file
  - name: python
    source: .vela-build-python-template.yml
    type: file

stages:
  build-java:
    steps:
      - name: java
        template:
          name: java

  build-react:
    steps:
      - name: react
        template:
          name: react

  build-react-vite-ts:
    steps:
      - name: react-vite-ts
        template:
          name: react-vite-ts

  build-python:
    steps:
      - name: python
        template:
          name: python

  # ----------- Deploy Dev - Java ----------------------
  deploy-dev-java:
    needs: [build-java]
    steps:
      - name: captain-deploy-dev-java
        image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
        ruleset:
          if:
            branch: [main]
            event: [push]
            path: ["java/*"]
        parameters:
          env: dev
          run_apply: true
          captain_file: java/.captain.yml
          version: "${VELA_BUILD_COMMIT:0:7}"
          edge_auth: false

  # ----------- Deploy Dev - Python ----------------------
  deploy-dev-python:
    needs: [build-python]
    steps:
      - name: captain-deploy-dev-python
        image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
        ruleset:
          if:
            branch: [main]
            event: [push]
            path: ["python/*"]
        parameters:
          env: dev
          run_apply: true
          captain_file: python/.captain.yml
          version: "${VELA_BUILD_COMMIT:0:7}"
          edge_auth: false

  # ----------- Deploy Dev - React ----------------------
  deploy-dev-react:
    needs: [build-react]
    steps:
      - name: captain-deploy-dev-react
        image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
        ruleset:
          if:
            branch: [main]
            event: [push]
            path: ["react/*"]
        parameters:
          env: dev
          run_apply: true
          captain_file: react/.captain.yml
          version: "${VELA_BUILD_COMMIT:0:7}"

  deploy-dev-react-vite-ts:
    needs: [build-react-vite-ts]
    steps:
      - name: captain-deploy-dev-react-vite-ts
        image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
        ruleset:
          if:
            branch: [main]
            event: [push]
            path: ["react-vite-ts/*"]
        parameters:
          env: dev
          run_apply: true
          captain_file: react-vite-ts/.captain.yml
          version: "${VELA_BUILD_COMMIT:0:7}"

  # ----------- Deploy Stage - React ----------------------
  deploy-stage-react:
    needs: [build-react]
    steps:
      - name: captain-deploy-stage-react
        image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
        ruleset:
          if:
            branch: [main]
            event: [push]
            path: ["react/*"]
        parameters:
          env: stage
          run_apply: true
          captain_file: react/.captain.yml
          version: "${VELA_BUILD_COMMIT:0:7}"
