metadata:
  template: true
  # list of vars that this template can consume
  # vars
  # package_dir

# https://go-vela.github.io/docs/templates/
# https://go-vela.github.io/docs/templates/tutorials/go/
# https://pkg.go.dev/text/template

steps:

  - name: build-java
    image: amazoncorretto:20-alpine-jdk
    ruleset:
      if:
        event: [ push ]
        branch: [ main ]
        path: [ "java/*" ]
    commands:
      - cd java && chmod +x ./gradlew
      - ./gradlew clean build -x test

  - name: docker-java
    image: docker-utilities.binrepo.cglcloud.in/enablementtools/docker-plugin:3-stable
    ruleset:
      if:
        event: [ push ]
        branch: [ main ]
        path: [ "java/*" ]
    parameters:
      repo: localdevjavaapp
      tags: "${VELA_BUILD_COMMIT:0:7}"
      dockerfile: java/Dockerfile
