FROM python:3.12-slim-bullseye as base

RUN sed -i 's/https/http/g' /etc/apk/repositories

RUN apk update && \
  apk upgrade --available 

RUN apk add git subversion

WORKDIR /app

ENTRYPOINT ["python3", "-m", "http.server"]
