---
kind: kubernetes
app: localdevjavaapp
type: web
team: apacappenablement
docker_image: &image_name localdevjavaapp
healthcheck:
  path: /greeting
container_port: 8080
internal: true
replicas: 1
# https://captain-docs.cglcloud.com/examples/kubernetes/security.html
# read_only_root_filesystem: false
dns:
  zone: cglcloud
  name: localdevjavaapp
envvars:
  dev:
    DD_ENV: dev
    DD_SERVICE: "localdevjavaapp"
    DD_TRACE_SPAN_TAGS: "env:dev"
    DD_LOGS_INJECTION: "true"
    DD_APM_ENABLED: "true"
    DD_LOGS_ENABLED: "true"
    DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
    DD_PROFILING_ENABLED: "true"
database:
  type: postgres
  flyway_path: scripts/flyway/sql
security:
  default:
    read_only_root_filesystem: false
    cap_drop_net_raw: true
    run_as_non_root: true
    allow_privilege_escalation: false
storage:
  nfs:
    data:
      path: /mnt/data
