FROM amazoncorretto:20-alpine-jdk

# RUN sed -i 's/https/http/g' /etc/apk/repositories
#
# RUN apk update && \
#   apk upgrade --available 

WORKDIR /app

COPY . ./


ENV HTTPS_PROXY http://web.prod.proxy.cargill.com:4200
ADD cacerts/*.pem /usr/local/share/ca-certificates/

# RUN $JAVA_HOME/bin/keytool -import -trustcacerts -file cacerts/cargill-m1-ca-2.cer -alias cargill-ca-m1 -cacerts -storepass changeit -noprompt
# RUN $JAVA_HOME/bin/keytool -import -trustcacerts -file cacerts/cargill-root-ca-2.cer -alias cargill-ca-ca2 -cacerts -storepass changeit -noprompt

# https://github.com/alpinelinux/docker-alpine/issues/160
# https://git.cglcloud.com/dxp/cgl-dxo-dxp-foundational-api-notification
RUN for f in cacerts/*.*; do echo "Import $f" && keytool -import -trustcacerts -file "$f" -alias "${f%}"  --cacerts -storepass changeit --noprompt; done

EXPOSE 8080

RUN chmod +x ./gradlew 

CMD ./gradlew -Dhttps.proxyHost=web.prod.proxy.cargill.com -Dhttps.proxyPort=4200 bootRun
