---
logging:
  level:
    org.springframework: INFO
    com.cargill.demo: INFO
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_CONNECTION}
  jpa:
    database: postgresql
